# Generated by Django 3.2.9 on 2021-11-15 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('is_disloyal', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prom_id', models.CharField(max_length=20)),
                ('date_creation', models.DateField()),
                ('ttn', models.CharField(default='', max_length=20)),
                ('status', models.CharField(choices=[('In_process', 'В процессе'), ('Done', 'Выполнен'), ('Canceled', 'Отменен')], max_length=200)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.customer')),
            ],
        ),
        migrations.CreateModel(
            name='ProductFromOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=200)),
                ('wholesale', models.IntegerField()),
                ('retail', models.IntegerField()),
                ('warehouse', models.CharField(max_length=200)),
                ('stock_number', models.CharField(max_length=200)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.order')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_date', models.DateField()),
                ('final_storage_date', models.DateField()),
                ('cost_of_delivery', models.IntegerField()),
                ('city', models.CharField(max_length=200)),
                ('post_office_number', models.CharField(max_length=400)),
                ('is_paid_delivery', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.order')),
            ],
        ),
    ]
