# Generated by Django 3.2.9 on 2021-11-15 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfromorder',
            name='sku',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'Новый'), ('In_process', 'В процессе'), ('Done', 'Выполнен'), ('Canceled', 'Отменен')], max_length=200),
        ),
    ]
