# Generated by Django 3.2.9 on 2021-11-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20211115_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfromorder',
            name='wholesale',
            field=models.IntegerField(null=True),
        ),
    ]
