# Generated by Django 3.2.9 on 2021-11-15 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_alter_productfromorder_wholesale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='arrival_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='cost_of_delivery',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='final_storage_date',
            field=models.DateField(null=True),
        ),
    ]
