# Generated by Django 3.2.9 on 2021-11-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_order_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productfromorder',
            name='image',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
