# Generated by Django 3.2.9 on 2021-12-25 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_auto_20211116_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ttn',
            field=models.CharField(default='ТТН не сформирована', max_length=20),
        ),
    ]
