# Generated by Django 3.2.9 on 2021-12-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_alter_order_ttn'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
    ]
