# Generated by Django 3.2.9 on 2022-01-11 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_rename_productfromorder_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product',
            new_name='name',
        ),
    ]
